### ISSUE TITLE
Docstring not proper for "password_profile_modify" api

### ISSUE THREAD

**Issue by tanmayx** [CiscoUcs/ucsc_apis#7]
ucsc_apis: Latest code
python version: 2.7.12

**Observation -**
The docstring for the **_password_profile_modify_** is not correct. The parameter types are all strings and not 'number' as mentioned below.

change_interval (number): change interval
no_change_interval (number): no change interval
change_count (number): change count
history_count (number): history count
expiration_warn_time(number): expiration warn time

**Comment by parag-may4** [comment]
Fixed by https://github.com/CiscoUcs/ucsc_apis/pull/10
